### ISSUE TITLE
Storage line and fill can be misaligned in plot_generation_time_series_stack

### ISSUE THREAD

**Issue by danielolsen** [Breakthrough-Energy/PostREISE#275]
# :beetle:

- [x] I have checked that this issue has not already been reported.

### Bug summary
Storage sub-figure in `plot_generation_time_series_stack` can be mis-aligned between the line and the fill_between.

### Code for reproduction
A minimum code snippet required to reproduce the bug. Please make sure to minimize the
number of dependencies required.
```python
import matplotlib.pyplot as plt
import pandas as pd
from powersimdata import Scenario
from postreise.plot.plot_generation_ts_stack import plot_generation_time_series_stack
scenario = Scenario(3861)
resources = list(scenario.get_grid().plant.type.unique()) + ["storage"]
time_range = [
    pd.Timestamp("2016-03-01 00:00:00", tz="US/Central"),
    pd.Timestamp("2016-03-07 23:00:00", tz="US/Central")
]
plot_generation_time_series_stack(
    scenario,
    "Louisiana",
    resources,
    time_zone="US/central",
    time_range=time_range,
)
plt.show()
```

### Actual outcome
![storage_fill_misalignment](https://user-images.githubusercontent.com/7348392/116453194-707cbc80-a813-11eb-8926-8fbf3d7cc37e.png)
Note: I made some changes to the axis labels here, but didn't touch anything with regard to the plotting itself.

### Expected outcome
Fill and line are aligned.

### Environment
Please specify your platform and versions of the relevant libraries you are using:
* Operating system: Windows
* PostREISE revision: 761aba6043d18ca3bc84b32f4ee3912dbe4d18fe
* Python version: 3.8.3

**Comment by BainanXia** [comment]
I found two problems: 
- `pg_storage.index.values` won't give same format of the x-axis, which is in `pg_storage.index` after we apply a new time zone. Replace the former with the latter will fix the problem.
![image](https://user-images.githubusercontent.com/52716585/116469718-1a6e4000-a838-11eb-9b8d-38002845f944.png)
![image](https://user-images.githubusercontent.com/52716585/116470345-ee9f8a00-a838-11eb-9321-137d3ce700d8.png)
- we mistakenly overwrite the axes of storage in [l.171](https://github.com/Breakthrough-Energy/PostREISE/blob/bec0eccefa24e6d687cbf9f60e5760faf6390849/postreise/plot/plot_generation_ts_stack.py#L171).

**Comment by danielolsen** [comment]
There was something else related to the time zones that I was running into, where I think sometimes the function wanted a pandas timestamp with a time-zone and sometimes it wanted a pandas timestamp without a time zone, and the error was about comparing timestamps with an without time zones. I don't have a good minimum working example to share right now though, I just added or removed a time zone as necessary to get things done.

**Comment by BainanXia** [comment]
> There was something else related to the time zones that I was running into, where I think sometimes the function wanted a pandas timestamp with a time-zone and sometimes it wanted a pandas timestamp without a time zone, and the error was about comparing timestamps with an without time zones. I don't have a good minimum working example to share right now though, I just added or removed a time zone as necessary to get things done.

I observed that when implementing the function. The logic is our time series doesn't come with a time zone by default, basically, if we query `df.index.tz`, it gives `None`. That's why we have to call tz_localize("UTC") first when changing time zone
![image](https://user-images.githubusercontent.com/52716585/116476975-9ae56e80-a841-11eb-8799-1fbdadb42d15.png)

None time zone will support timestamps slicing without time zone. If a time series has a time zone defined, we will need timestamps with time zone defined as well. Otherwise, following error will be raised:
![image](https://user-images.githubusercontent.com/52716585/116477279-03345000-a842-11eb-925b-63792918fa77.png)
![image](https://user-images.githubusercontent.com/52716585/116477336-147d5c80-a842-11eb-8eb5-5ecb8daaa5a2.png)

Since, we will do `change_time_zone` anyways (regardless of `tz="utc"` or not)  in the current implementation:
![image](https://user-images.githubusercontent.com/52716585/116477706-9a010c80-a842-11eb-850e-ffa246b106df.png)

We will always require the timestamps for slicing having time zone defined, even it is not provided, the defaults are like following: 
![image](https://user-images.githubusercontent.com/52716585/116477659-8655a600-a842-11eb-86e8-6a49d129eb16.png)

However, as I mentioned in the [PR](https://github.com/Breakthrough-Energy/PostREISE/pull/276), when the user specify time range for slicing, it is unnecessary to specify the `time_zone` keyword argument in the function call, i.e. we can slice a "utc" time series with "UC/Central" timestamps directly.

**Comment by rouille** [comment]
We could set the time zone when we read the data in the `InputData` and `OutputData` classes.

**Comment by BainanXia** [comment]
> We could set the time zone when we read the data in the `InputData` and `OutputData` classes.

If time zone is always defined in the time series that we are working with, we can add input checks in `slice_time_series` to make sure the timestamps have time zone defined.
